spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*" # 允许所有的请求头携带过来
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:

        # 鉴权服务
        - id: oauth
          uri: lb://oauth
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
                args:
                  key-resolver: '#{@md5KeyResolver}'
                  redis-rate-limiter.burstCapacity: 3
                  redis-rate-limiter.replenishRate: 2


  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka