server:
  port: 8001
spring:
  application:
    name: oauth
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/elevator-management?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: changgou.com # 前面不需要加点。cookie中自动添加【点】 设置一级域名即可
  cookieMaxAge: -1

jks:
  name: changgou.jks
  storepassword: changgou
  keypassword: changgou
  alias: changgou

logging:
  level:
    org.lufengxue.searchsql.mapper: debug